### ISSUE TITLE
Version Better

### ISSUE THREAD

**Issue by tsquire5** [manywho/ManyWho_Flow_SDK_Java#3]
Currently versioning is done via a hardcoded string in the application (https://github.com/manywho/service-twilio/blob/develop/src/main/java/com/manywho/services/twilio/Application.java#L22) this is a bit crap. it would be better to extract this into the pom and possibly integate with some DI tooling like bamboo

**Comment by jonjo-manywho** [comment]
I don't think this is something that should be in the SDK - it's totally up to the application layer to define the endpoint to be used for a service (which might not even be versioned).

If the service builder follows our versioning recommendations (SemVer basically), then that endpoint will only change in the rare case when a new Major version is released, which will usually be because of a major rewrite. So I'm not sure it should be configurable from the SDK's point of view.

If you think it's something that _really_ should be in the SDK, feel free to create a pull request and I'll have a look!

**Comment by tsquire5** [comment]
Yeah, its more the sdk enforcing a versioning convention than a url convention. Ill do a quick pull request as an example
